version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/football.db:/app/football.db
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend